### PR TITLE
Zabbix-5.0.5

### PR DESCRIPTION
**Pull request by DONCIEUX-CAMILLE**
At this moment, upgrade is impossible to 5.2.1.

### CODE REVIEW

**Comment by DONCIEUX-CAMILLE** [comment]
The upgrade is freezing from 4.4.7 to 5.2.1 at 87%
The upgrade is freezing from 5.0.5 to 5.2.1 at 67%

**Comment by hKevin67** [comment]
Hello I looked on your profile but I did not find a version zabbix 5.0 for the following different architectures: 
rs 820+ = denverton x20series
rs 818+ = avoton x18 series
ds216+ = braswell x16 series

I found only for armada38x

is it possible a version 5.0 for this different model?

thank you in advance for your answer

**Comment by DONCIEUX-CAMILLE** [comment]
Hi @hKevin67 
At first, I wanted to compile only 5.2 for all architectures and skip 5.0. 
But I discovered an upgrade bug with my own database from 4.4 to 5.2.
That's why you only find armada38x 5.0 in my repository to test and understand the bug before opening a ticket in Zabbix.
At this moment, I didn't have enough time to go further.
So, Ok, I will provide all the architectures that I'm used to compile.
Camille

**Comment by GuillaumeHullin** [comment]
Hi there,
Any chance you could compile with --with-openssl ? I would need armada375.
Best would be if you could point me on some good source so I could do the compile myself.
Guillaume

**Comment by GuillaumeHullin** [comment]
> Hi there,
> 
> Any chance you could compile with --with-openssl ? I would need armada375.
> 
> Best would be if you could point me on some good source so I could do the compile myself.
> 
> Guillaume

By the way.... I'm following https://github.com/SynoCommunity/spksrc/wiki/Developers-HOW-TO ... is there a repo somewhere you would store the makefile that you use during your cross compilation?
Guillaume

**Comment by DONCIEUX-CAMILLE** [comment]
@GuillaumeHullin 
Hi Zabbix version 5.0.8 now compiled with open-ssl support. It was easy since it was already compiled with libcurl compiled with openssl.
Please have a look on branch 5.0.8
Camille

**Comment by GuillaumeHullin** [comment]
@DONCIEUX-CAMILLE Thanks for the update :)
I would love to experiment it also myself, could you post or send me your config for this cross-compilation? I did manage to follow the HOW-TO for spksrc (I used a VM Debian, not Docker) but it's actually my first cross-compilation and so I nicely failed when I tried.
Guillaume

**Pull request closed without merging**
