### PR TITLE
Zabbix 4.4.0

### PR DESCRIPTION
**Pull request by DONCIEUX-CAMILLE**
https://www.zabbix.com/whats_new_4_4

### CODE REVIEW

**Comment by DONCIEUX-CAMILLE** [comment]
Zabbix 4.4.4 now

**Comment by DONCIEUX-CAMILLE** [comment]
@thetuxinator @mcdull
Could you please delete your fork of the Zabbix 4.4.0 branch. This branch is no longer supported as now the default branch is 4.4.7.

I want to delete this branch and I can't since you fork this 4.4.0 branch.

THANKS A LOT
Camille.

**Comment by thetuxinator** [comment]
Hi, just my opinion, why do you delete that branch already now? Archiving or locking would be a better option, imagine you maybe have a case in future, where you want to compare behaviour with old vs new because you hunt a bug? will of course delete my branch. regards Tuxinator

**Comment by thetuxinator** [comment]
actually i can't even find a branch i created?

**Comment by DONCIEUX-CAMILLE** [comment]
Ok, will archive the branch

**Pull request closed without merging**
