### PR TITLE
Zabbix 4.4.7

### PR DESCRIPTION
**Pull request by DONCIEUX-CAMILLE**
Latest Zabbix version in 4.4. update 7

### CODE REVIEW

**Comment by cnopix** [comment]
@DONCIEUX-CAMILLE 

hi,

i test the avoton version and i. have the same problem like 4.4.4 . Can you check ? thanks :-)

Arf, it's not possible to downgrade :s

**Comment by DONCIEUX-CAMILLE** [comment]
@cnopix 
It's normal, To have proxy, you must install it for the first time.
You could let appear the proxy if you're creating the file /var/packages/zabbix/target/var/proxy.enabled
The downgrade procedure is DSM behaviour.  Not under my package.

**Comment by cnopix** [comment]
@DONCIEUX-CAMILLE 

Yes, sorry it works. i remove the old one and i keep database and it works now. :-)

thx.

**Comment by DONCIEUX-CAMILLE** [comment]
@infopro-67
Compilation done and available for braswell package. :-)

**Comment by DONCIEUX-CAMILLE** [comment]
@gianlucaromito
Compilation done for armada375. To have proxy access when a former installation has been done, you must desinstall the former package (you can keep the former database) and re-install the new one.

**Comment by DONCIEUX-CAMILLE** [comment]
@jcacc
Could you please confirm that your package architecture is pineview ?
Because I have 10H of compilation for nothing if not...
Camille.

**Comment by infopro-67** [comment]
Hello.

Thanks for the Braswell package.
I find a small bug. I try to open zabbix-agent conf files, but got this error :
Error in opening /usr/local/zabbix/etc/zabbix_agent.conf !
In the agent log, i see that the conf files is  /usr/local/zabbix/etc/zabbix_agent.conf**d**

**Comment by DONCIEUX-CAMILLE** [comment]
@infopro-67 
Yes, exact, I've prepared all the things for Zabbix agent 2 in GO, and remove all the things with D, and forgotten some places...
I will fix it for next release.
Thanks.

**Comment by DunklesKaltesNichts** [comment]
Is an SPK for a DS213 with 88f628x possible?
2Ghz Single Core with 512MB Ram
DSM 6.2.2-24922 Update 4

Regards

**Comment by DONCIEUX-CAMILLE** [comment]
@RenFle18 
Hi. Done, could you confirm that Zabbix agent is running and inside the GUI everything is working.
Thanks
Camille.

**Comment by DunklesKaltesNichts** [comment]
Installation: OK (zabbix server)
zabbix controls: everything seems to work except starting and stopping the agent.
zabbix web gui: 
error 500 >The switch from Nginx to Apache as backend works

**Comment by DONCIEUX-CAMILLE** [comment]
@RenFle18 
I guess that I have fixed the problem with agent. It's due to I've prepared lots of things for agent GO and in the makefile (outside the package) between the previous packages and yours. ( I miss the D in the path for the previous agent...)
I've re-upload the fix. Could you try it ?
You must desinstall the previous package from synology and resinstall it. Don't delete your previous database.
Camille

**Comment by DunklesKaltesNichts** [comment]
After a few attempts, further problems have appeared.
error messages in Zabbix Web Frontend: DB type "MYSQL" is not supported by current setup."
a consistently high CPU load on the DS213 makes the DS213 unusable.
lots of messages about slow SQL queries in the logfile of the Zabbix server.

i think the DS213 is simply too slow.

then the package requires php 5.6 and MariaDB 5, although newer packages and versions are available.

well, thanks for trying.

maybe a packet is only posible with the agent, then it is possible to monitor the DS213 via the agent and has an alternative to SNMP.

**Comment by DONCIEUX-CAMILLE** [comment]
@RenFle18 
I've tested on my local synology and fixed everything about the agent.
If you want just to only start the agent and not the server, you can do that in deleting the file /var/packages/zabbix/target/var/server.enabled
But remember that starting server and proxy on the same synology is a non sense. That's why the package is proposing the choice between proxy and server.
The agent is always started.
Camille

**Comment by DONCIEUX-CAMILLE** [comment]
@RenFle18 
Concerning the pb of error messages in Zabbix Web Frontend: DB type "MYSQL" is not supported by current setup."
Are you using the PHP5.6 in your webstation ?

In the installation process, I've hardcoded 
ln -fs /var/packages/zabbix/target/zabbix.ini /usr/local/etc/php56/conf.d
synoservicectl --restart pkg-WebStation-php56

So the package is using PHP5.6 and not an other else.
NB : The minimum prerequisite for Zabbix 4.4 is PHP5.4

**Comment by DunklesKaltesNichts** [comment]
yes, I was using PHP 5.6, with Apache 2.4 and mariaDB 5. II'll try again this weekend.

**Comment by thetuxinator** [comment]
Hi, 
as i could not find a place where to open issues, i ask here. i upgraded with your latest spk file on a ds218+ and the webinterface is inaccesible with a 403 forbidden error.

thanks in advance for any help

kind regards

**Comment by DONCIEUX-CAMILLE** [comment]
@thetuxinator 
Hi
Very odd since I didn't changed anything on this part and I'm upgrading the package on my Synology without problem.
The package is just deleting the web interface in case of proxy installation.
You are just using Zabbix Server on your Synology ?

Otherwise, the best way to fix is to desinstall the package with database keeping. Be careful just to save before the /var/packages/zabbix/target/etc/zabbix_agentd.conf.d directory in case of user Parameter configuration.
The package during the reinstallation will detect the previous database and won't erase anything.
Camille

**Comment by thetuxinator** [comment]
I am only using Zabbix Server there, ok i will try your suggestion, the strange thing is, while Zabbix Server works and is even sending notifications, only the webaccess doesn't work

**Comment by infopro-67** [comment]
Hello.

Did you know how to start zabbix agent using CLI in SSH ?

Thanks

**Comment by DONCIEUX-CAMILLE** [comment]
@infopro-67 
Very easy : logged as root user on your NAS
/usr/local/zabbix/sbin/z_agent_start_stop.sh stop|start|restart
There is a sudo inside the script which is launching the command as zabbixagent user.
Regards
Camille

**Comment by DONCIEUX-CAMILLE** [comment]
Upgrade to latest version

**Pull request closed without merging**
