### PR TITLE
Zabbix 5.0.8

### PR DESCRIPTION
**Pull request by DONCIEUX-CAMILLE**
Latest update.
Compilation with openssl

### CODE REVIEW

**Comment by GuillaumeHullin** [comment]
@DONCIEUX-CAMILLE Thanks for the update :)
I would love to experiment it also myself, could you post your config for this cross-compilation? I did manage to follow the HOW-TO for spksrc (I used a VM Debian, not Docker) but it's actually my first cross-compilation and so I nicely failed when I tried.
Guillaume

**Comment by DONCIEUX-CAMILLE** [comment]
@GuillaumeHullin 
The main problem is not zabbix itself, but all the dependencies. So I need to synchronize all my repository. I will think to put it in my dev branch here. But not in the next days..too busy.
Camille

**Comment by GuillaumeHullin** [comment]
@DONCIEUX-CAMILLE yeah I think that's best if you could put that in a separate branch. But no rush, do it when you can. Meanwhile I'll try your latest compilations.
Guillaume

**Comment by DONCIEUX-CAMILLE** [comment]
Latest compilation for 5.0

**Pull request closed without merging**
