### PR TITLE
Zabbix 4.4.4

### PR DESCRIPTION
**Pull request by DONCIEUX-CAMILLE**
Latest Zabbix version 4.4.4

### CODE REVIEW

**Comment by espetoet** [comment]
Hello! my synology model and bromolow ds3615xs dsm 6.2.2.24922 cpu. could make one that works on it thank you

**Comment by DONCIEUX-CAMILLE** [comment]
@espetoet 
Hi
Done.
This package doesn't contain at this moment proxy and agent2.
Thanks
Camille

**Comment by espetoet** [comment]
thanks

**Comment by jcacc** [comment]
Hello, I hope I'm doing this right. I looked up the model of my Synology (DS2411+) and it said the model is "x86". Which version would be right for me or would you recommend the manual install?

Thanks!
Joe


Disregard, I read further down the page. I'm a dummy. :)

**Comment by DONCIEUX-CAMILLE** [comment]
@jcacc 
Could you send me the result of the command line 
uname -a
on our Synology, just to be sure.
I'm thinking about pine view, but not sure.
Camille

**Comment by jcacc** [comment]
Hi Camille,

Thanks for responding. Here ya go. 

`Linux DiskStation 3.10.105 #24922 SMP Wed Jul 3 16:37:05 CST 2019 x86_64 GNU/Linux synology_x86_2411+
`

**Comment by DONCIEUX-CAMILLE** [comment]
@jcacc
According to me, the packet architecture for you is pinewiew.

**Comment by Oxhyd** [comment]
Hi, my zabbix is under version 4.2.8 and I would like a spk for my synology model which is: DS215J 
thx

**Comment by DONCIEUX-CAMILLE** [comment]
HI
@Oxhyd 
Could you confirm me that your packet architecture is Armada375
@jcacc 
Could you confirm me that your packet architecture is pinewiew

I will try to provide the packages asked in the next few days.
Camille confined at home !

**Comment by Oxhyd** [comment]
Yes, it’s armada 375 88F6720
Thx 

I have a question regarding the DSM version
I am currently in 6.2.2
If I decide to update, will your package continue to work? (if version 7 is released?)

**Comment by DONCIEUX-CAMILLE** [comment]
@Oxhyd 
I've finished to compile the package for Armada375. Available in the new branch 4.4.7.
[https://github.com/DONCIEUX-CAMILLE/zabbix-spk/tree/Zabbix-4.4.7]
I'm compiling in 6.2 to provide as many people as possible.
The DSM version is so far backward compatible. So no problem to upgrade the DSM version.

**Comment by Oxhyd** [comment]
Thank you very much, will it work towards my zabbix server in 4.2.8?

**Comment by DONCIEUX-CAMILLE** [comment]
@Oxhyd 
As a Zabbix administrator, I will answer that Zabbix Server and Zabbix Proxy MUST have the same version.
[https://www.zabbix.com/documentation/4.4/manual/appendix/compatibility](url)
Only Zabbix agent could have different versions.

If you have a small database and not much history trends, the upgrade is quite fast. You have just to change the Zabbix Server binary and restart, the upgrade will be launched automatically.

**Comment by infopro-67** [comment]
Hello.

Is it possible to compile package for a DS216+ ( Braswell ) ?

Thanks

**Comment by DONCIEUX-CAMILLE** [comment]
@infopro-67 
Hi
I've starting your compilation. Result in 10H.
Camille.

**Pull request closed without merging**
