### PR TITLE
Zabbix 4.2.4

### PR DESCRIPTION
**Pull request by DONCIEUX-CAMILLE**

### CODE REVIEW

**Comment by pterrien** [comment]
Hi,

Thanks for providing this very useful package.
I may have found an issue, as the package fails to install properly on my Synology.
Sorry to use the PR thread for this, I couldn't find any other way to contact you or open an issue.

**Environment:**
_package version:_ zabbix_cedarview-6.2_4.2.4-1.spk
_DSM version:_ 6.2.2-24922 Update 3
_hardware / arch:_ DS1513+ / Cedarview

**Description:**
The package seems to install properly, but none of the services will actually start.
The only error messages displayed in Zabbix Controls are: 
> Error in opening /usr/local/zabbix/var/zabbix_XXXX.log (XXX being server, agentd, proxy)

**Investigations:**
Taking a look to `/var/log/packages/zabbix.log`, we see interesting things:
> /var/packages/zabbix/scripts/installer: line 101: [: -neq: binary operator expected
> /var/packages/zabbix/scripts/installer: line 108: adduser: command not found
> ...

As you know, starting from DSM 6 (maybe 5, too?), the adduser, deluser, ... commands are not part of the standard DSM env anymore, but they can be provided in each third-party package thanks to busybox.

In this case, line #101 of `scripts/installer` is responsible for checking the DSM version, however there is a small bug in it:
> if [ "$SYNOPKG_DSM_VERSION_MAJOR" **-neq** "4" ]; then
>     # Install busybox stuff
>     ${INSTALL_DIR}/bin/busybox --install ${INSTALL_DIR}/bin
> fi

should be replaced by:
> if [ "$SYNOPKG_DSM_VERSION_MAJOR" **-ne** "4" ]; then
>     # Install busybox stuff
>     ${INSTALL_DIR}/bin/busybox --install ${INSTALL_DIR}/bin
> fi

**-neq** not being a valid operator, **-ne** should be used instead.

Note: For other people facing this issue and looking for a quick workaround:
- just download the package, and uncompress it to a temporary folder (it is a TAR archive)
- modify the `scripts/installer` as indicated below
- compress the folder back as TAR, and rename it as *.spk
- install manually in DSM as usual

I hope you will find this useful, and most of all: many thanks for your work on it, having Zabbix running on DSM is definitely a great feature!

Cheers,

Pascal.

**Comment by DONCIEUX-CAMILLE** [comment]
Hi

Thank you so much. I never noticed this bug and you are right and I remembered that when I wrote the line, I’ve just put an n before the eq without removing the q….
I will update the package for all environments since a new version of Zabbix has been delivered at the end of July. With the vacations, I didn’t get the time to recompile the latest version.

Thanks

Camille.

**Comment by DONCIEUX-CAMILLE** [comment]
Hi 
For DS418, it's rtd1296 architecture. I will have a look to compile for it.
If yes, the package will be available for Zabbix 4.2.6 that I'm currently compiling

**Comment by DONCIEUX-CAMILLE** [comment]
Hi
Enjoy RTD1296 delivered for DSJ418 with Zabbix 4.2.6 !
Bye
Camille

**Pull request closed without merging**
