### PR TITLE
Zabbix-5.4.1

### PR DESCRIPTION
**Pull request by DONCIEUX-CAMILLE**
Zabbix 5.4.1 release

### CODE REVIEW

**Comment by gianlucaromito** [comment]
Hello and thanks for the great work. I've installed it on 2 NAS and it works perfectly. I've a question: is it possible that you make a package for the MARVELL Armada XP MV78230 (This CPUis installed in the RS814) and for the INTEL Pentium N3710
(installed in the DS916+). Thank you!

**Comment by DONCIEUX-CAMILLE** [comment]
@gianlucaromito 
Hello. I've done this night the compilation for armadaXP and zabbix 54.1. I will push it to this branch when you will delete your useless fork of my 4.4.4 repository.
Thanks
Camille

**Comment by gianlucaromito** [comment]
Thank you! It should be deleted now.
Gianluca

**Comment by DONCIEUX-CAMILLE** [comment]
@gianlucaromito 
Thanks, compilation ArmadaXP 6.2 on line.

**Comment by gianlucaromito** [comment]
Perfect! installed and works as expected. Thanks so much!

**Comment by DONCIEUX-CAMILLE** [comment]
@gianlucaromito you're welcome
Camille

**Comment by johnwc** [comment]
Can we get new packages for the new Synology DSM 7?

Sorry for posting this here, but there is no where to create a new issue item for something like this.

**Comment by DONCIEUX-CAMILLE** [comment]
Hi @johnwc 
At first, could you be more accurate about what you are asking since compile for each cpu takes some times.
After that, system is normally retro compatible, so at this moment, there is no need to upgrade the system.
At the end, I will create new packages for the next version of Zabbix when the 6.0 will be available.
Sorry to not complete your request.
Camille

**Comment by johnwc** [comment]
We have several different models of disk stations installed at our remote locations, so we would need a package for each individual platform we have. The DSM 6 packages do not work from DSM 7. Can you share the procedure and scripts that you use to create these packages, so that others can build them on our own if we need to. We are more than happy to compile for each platform, but we need to understand the process to do so.

**Comment by johnwc** [comment]
Think you can share that with us?

**Comment by DONCIEUX-CAMILLE** [comment]
@johnwc 
Hi 
At this moment, no. I don't have enough time to share all my work.
I'm reading the prerequisites for DSM7.0 : If my package is not working on this version, it's because I never take time to read the documentation to sign it. It's the only point that I have to fix before going further and all the packages will work even if it is compiled with previous Synology version.
Camille

**Comment by johnwc** [comment]
Can you not commit the work to this repo? We can figure out how to use it.

**Comment by DONCIEUX-CAMILLE** [comment]
It's not just like this... you must create the whole env with the good toolchain and the prerequisites in the cross folder. So I don't want to commit all the cross that I'm using since it's for me a non-sense in this Zabbix repository. 
Other question, you don't need Zabbix Server on your different synologies, you only need the zabbix agent ?
Camille

**Comment by johnwc** [comment]
Do you not have the setup of all the requirements in the cross folder as a shell script? So that you can easily reproduce your environment? Like a build script?

We need the proxy. Our installs are remote site monitoring of our network equipment.

**Comment by johnwc** [comment]
@DONCIEUX-CAMILLE can I donate or buy you a coffee/beer to entice you? 😂 We really need this badly.

**Comment by DONCIEUX-CAMILLE** [comment]
@johnwc It's not a problem of will and money. I don't have enough time during the next 2 weeks to achieve the new package.
I will have more time just before Christmas as my kid won't be there.
I will upgrade my own Synology as pre-requisites to be sure that I will commit a package working.
I've starting to read the documentation about 7.0, downloading the new toolchain to compile. Even that, creating he toolchain env is more than 15 minutes peer toolchains.
At first I was expecting the latest zabbix version (still in alpha today) to recreate the new packages.
Other things : could you provide me
- the exact list of which synology toolchain you need, apollolake, armadaxx, etc
- the Zabbix version of proxy since I remember you that Zabbix Server and Zabbix proxies MUST be at the same level.
Thanks
Camille

**Comment by johnwc** [comment]
Well I hope when you create the new environment for DSM 7, you create it with scripts? So that it can be shared for others to use and learn from, as well as be easily recreated on another machine.

Our Disk stations we have currently.
RS1619xs+
DS916+
DS918+
RS820+
DS1517+

**Comment by johnwc** [comment]
@DONCIEUX-CAMILLE how's everything going with this?

**Comment by DONCIEUX-CAMILLE** [comment]
@johnwc Unfortunately not. I'm currently working on it since 10 days and a lot of prerequisites are not working.
So, I'm debbugging the compilation. After that, when compilation will work, I will have to review the package itself to install it on 7.0.
Camille.

**Comment by DONCIEUX-CAMILLE** [comment]
PS : you didn't answer me about the target zabbix version you need. As I explained you, you must have the same version between proxy and Zabbix Server.
Camille

**Comment by johnwc** [comment]
We are using 5.4.1. How is the guide for the steps to reproduce what you are doing? Are you creating that while you are working on this? If so, can you share what you have so far? We may be able to start working together with debugging the process.

**Comment by johnwc** [comment]
Any progress? 😀

**Comment by DONCIEUX-CAMILLE** [comment]
@johnwc First, Happy new year :-)
I've finishing the compilation for my own Synology. I'm studying the news scripts for installation and stop/start on DSM7.
I've beginning to upgrade my own Synology to verify the package to finish the dev.
Camille

**Comment by johnwc** [comment]
Happy new year! 🎉 That's great news! Did you happen to update the docs/scripts on how to reproduce it?

**Comment by johnwc** [comment]
@DONCIEUX-CAMILLE How's everything going? If you'd rather email than post on here, you can email me at johnwcarew at gmail

**Comment by thetuxinator** [comment]
Any news on this? Really interested in Dsm 7 support as my upgrade-plans are blocked at the moment!

**Comment by DONCIEUX-CAMILLE** [comment]
@thetuxinator Hi. The Zabbix package for DSM7.0 and 5.4.1 is done. I was exchanging directly with John about it and waiting for his feedback.
But, with DSM 7.0, the package can't be installed as root, and manually actions must be done after the installation like changing the fping owner.
As Zabbix 6.0 LTS is at the end available, I was expecting to provide 6.0 package with DSM 7.0.
But be careful, because on my own DSM, a lot a CPU/memory is consuming.
Camille

**Comment by thetuxinator** [comment]
> @thetuxinator Hi. The Zabbix package for DSM7.0 and 5.4.1 is done. I was exchanging directly with John about it and waiting for his feedback. But, with DSM 7.0, the package can't be installed as root, and manually actions must be done after the installation like changing the fping owner. As Zabbix 6.0 LTS is at the end available, I was expecting to provide 6.0 package with DSM 7.0. But be careful, because on my own DSM, a lot a CPU/memory is consuming. Camille

Ok, thx a lot for the efforts, what about asking synology if it's possible somehow without manual interaction?
regards

**Comment by DONCIEUX-CAMILLE** [comment]
@thetuxinator 
Extract of dsm7.0 dev guide :
    Adjustment to lower the privilege level for third-party packages to run as a user rather than root. Package installation would fail if its privilege setting differs from our new requirement.
    To avoid future update issues, It is highly recommended that your package can be modified to match our new lower privilege framework. Please develop according to the new developer’s guide provided

**Comment by thetuxinator** [comment]
> @thetuxinator Extract of dsm7.0 dev guide : Adjustment to lower the privilege level for third-party packages to run as a user rather than root. Package installation would fail if its privilege setting differs from our new requirement. To avoid future update issues, It is highly recommended that your package can be modified to match our new lower privilege framework. Please develop according to the new developer’s guide provided

As i am also a Linux System Engineer since many years, what exactly has to be run with high privilege? Maybe there is a way around. Actually are there already packages available for testing?

**Comment by DONCIEUX-CAMILLE** [comment]
@thetuxinator 
the main pb is 
chmod 4710 /var/packages/zabbix/target/sbin/fping as root.
I have 2 packages ready for armada38x and apollolake
What package in priority do you need ?

I wanted to create package with 6.0.1 in the new few days.
Camille

**Comment by thetuxinator** [comment]
> @thetuxinator the main pb is chmod 4710 /var/packages/zabbix/target/sbin/fping as root. I have 2 packages ready for armada38x and apollolake What package in priority do you need ?
maybe we could adress that to synology? as fping really needs root, or is there a way to run fping from a container ? do containers run as root in syno? so we could workaround that and maybe use docker exec as a fping cmd :D 
> 
> I wanted to create package with 6.0.1 in the new few days. Camille

I need the apollolake versions.
i am unsure now how to proceed, i am on dsm 6.x and want to upgrade to 7.x so how to proceed? what will occur if upgrade to dsm 7? will the installed zabbix stop working? do i have to uninstall first?

**Comment by DONCIEUX-CAMILLE** [comment]
@thetuxinator 
If your database is not in mariadb10 on your dsm6.x, first, dump your db, upgrade in mariadb10. redo a dump In case of...
Then upgrade DSM in 7.0. 
The whole will take more than 2H.
All packages which are incompatible will be stopped and put in quarantine. Then install the new DSM7.0 zabbix packages. Normally you don't lose your zabbix datas. (that's why dump is necessary in case of pb)
Camille

**Comment by thetuxinator** [comment]
a completely different question, why is there no way of opening issues in your fork? https://github.com/DONCIEUX-CAMILLE/zabbix-spk ?

**Comment by thetuxinator** [comment]
a guy over at bb-qq's 2.5 gbit driver for synology had a good idea, do a scheduled task for the command we need to manualy run which is run as root after install :D see https://github.com/bb-qq/r8152/issues/203

**Comment by thetuxinator** [comment]
No matter what i do, always results in the message "Must apply on root this command : chmod 755 /volume1/web_packages in order to have frontend working and backup on upgrade working.If Proxy installed, no GUI
" when trying to access the gui

**Comment by DONCIEUX-CAMILLE** [comment]
@thetuxinator 
Yes, I had to find a workaround to force people to launch the chmod. Otherwise, the package can't copy the zabbix.conf.php in the target web folder... Extract of the command line in the package as you are admin, you will understand the code :
# apply changes in web folder
                # by default maintenance msg with apply chmod to have user sc-zabbix working
                ls ${WEB_DIR}/zabbix/conf 2>&1 > /dev/null
                if [ $? -eq 0 ] ; then
                        cp ${INSTALL_DIR}/target/share/zabbix/conf/zabbix.conf.php ${WEB_DIR}/zabbix/conf
                        if [ "${wizard_installation_proxy}" == "true" ] ; then
                                cp ${WEB_DIR}/zabbix/conf/maintenance_proxy.inc.php ${WEB_DIR}/zabbix/conf/maintenance.inc.php
                        else
                                cp ${WEB_DIR}/zabbix/conf/maintenance_ok.inc.php ${WEB_DIR}/zabbix/conf/maintenance.inc.php
                        fi
                fi

 The file maintenance is used by zabbix administrator to put the GUI in maintenance mode. put // in the maintenance.inc.php before the warning_msg
//$_REQUEST['warning_msg']
and verify that your zabbix.conf.php has the correct values.
I made a lot of uninstall/install and perhaps forgot to be more accurate on this step.
I tried on update with the same package working.
Camille

**Comment by thetuxinator** [comment]
Got all working now, however have to mention i did a fresh install now and restored the database afterwards again. This time it was working.

**Comment by DONCIEUX-CAMILLE** [comment]
@thetuxinator 
I will update the message to say : chmod 755 /volume1/web_packages and then reinstall the package without uninstalling.

**Comment by rohrbachger** [comment]
I would like to run zabbix 6 in dsm7 apollolake
I tried to cross compile, but I'm running into issues with mariadb. 
Cam you give Sole hinter dir cross compiling, e.g the make file you are using

**Comment by DONCIEUX-CAMILLE** [comment]
@rohrbachger : have a look on devel branch please.

**Comment by DONCIEUX-CAMILLE** [comment]
Compilation for 6.2.1 in progress in a new branch

**Comment by rohrbachger** [comment]
Cool, I got it. Will test it

**Pull request closed without merging**
